TYPE: 'ATTACK'

HYPERPARAMETERS:
    BATCH_SIZE: 1
    PRINT_FREQ: 10

DATASET:
    NAME: 'CIFAR10'
    TRAIN: FALSE
    CLASSES: 10
    DIR_PATH: 'datasets/'
    NORMALIZE: FALSE
    CROP: FALSE
    
ATTACK:
    NAME: "PGD"
    STEP: 'ADV'
    MAX_ITER: 10
    MOMENTUM: 0
    EPSILON:
        TYPE: 'FIXED'
        VALUE: 4
    ALPHA:
        TYPE: 'DIVISOR'
        DIVISOR: 10
    INIT:
        TYPE: 'RAW'


MODELS:
    # Model used to generate adversarial examples (ATTACK model)
    ADV_MODEL:
        NAME: "WideResNet"
        DEPTH: 28
        WIDEN_FACTOR: 10
        DROP_RATE: 0
        PARALLEL: TRUE
        PRETRAINED: TRUE
        CHKPT_PATH: "chkpt/chkpt_scaled/chkpt_plain__model_best.pth.tar"
    
    # Model we are trying to fool
    THREAT_MODEL:
        NAME: "WideResNet"
        DEPTH: 28
        WIDEN_FACTOR: 10
        DROP_RATE: 0
        PARALLEL: TRUE
        PRETRAINED: TRUE
        CHKPT_PATH: "chkpt/chkpt_scaled/chkpt_plain__model_best.pth.tar"

PATHS:
    RESULTS: 'results/'

