TYPE: 'DEFENSE'

HYPERPARAMETERS:
    BATCH_SIZE: 64
    EPOCHS: 30
    OPTIM:
        NAME: 'ADAM'
        LEARNING_RATE: 0.001
        WEIGHT_DECAY: 0
        SCHEDULER:
            NAME: 'STEP'
            EPOCH: 25
            LR_DECAY: 0.1
    PRINT_FREQ: 10

DATASET:
    NAME: 'CIFAR10'
    CLASSES: 10
    DIR_PATH: 'datasets/'
    SHUFFLE: TRUE
    NORMALIZE: FALSE
    CROP: FALSE
    
ATTACK:
    NAME: 'PGD'
    STEP: 'ADV_HGD'
    MAX_ITER: 7
    MOMENTUM: null
    # [CONSTANT(4), DYNAMIC(MAX_ITER), RANDOM_RANGE]
    EPSILON:
        TYPE: 'RANDOM'
        VALUE: null
        MIN_VAL: 0
        MAX_VAL: 17
    ALPHA:
        TYPE: 'DIVISOR'
        # Denominator to compute alpha: alpha = EPSILON / DIVISOR
        DIVISOR: 4
    INIT:
        TYPE: 'RAW'


MODELS:
    # Model we seek to train
    THREAT_MODEL:
        NAME: 'HGD'
        INPUT_WIDTH: 32
        INPUT_HEIGHT: 32
        TRAIN: TRUE
        PARALLEL: TRUE
        DENOISER_PATH: null
        TARGET:
            NAME: "WideResNet"
            DEPTH: 28
            WIDEN_FACTOR: 10
            DROP_RATE: 0
            PARALLEL: TRUE
            PRETRAINED: TRUE
            CHKPT_PATH: "chkpt/kwta2/model_best.pth.tar"
            ACTIVATION:
                NAME: 'k-WTA2D'
                SPARSITY_RATE: 0.2
            LOSS:
                NAME: 'SCE'
                CLASSES: 10
                REDUCTION: 'mean'
        ACTIVATION:
            NAME: 'ReLU'
    
    # Model we are trying to fool
    ADV_MODEL:
        NAME: 'WideResNet'
        DEPTH: 28
        WIDEN_FACTOR: 10
        DROP_RATE: 0
        PARALLEL: TRUE
        PRETRAINED: TRUE
        CHKPT_PATH: "chkpt/kwta2/model_best.pth.tar"
        ACTIVATION:
            NAME: 'k-WTA2D'
            SPARSITY_RATE: 0.2
        LOSS:
            NAME: 'SCE'
            CLASSES: 10
            REDUCTION: 'mean'

    
PATHS:
    SAVE_DIR: 'chkpt/denoiser_ifgsm7_kwta2/'
    SAVE_NAME: 'model_best.pth.tar'
    RESULTS: 'results/'

LOGGER:
    DIR: ''
    FILE: 'experiments.txt'